apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: alexandraioan/api-gateway
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8005
---

apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip-srv
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 8005
      targetPort: 8005

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gatewaydb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gatewaydb
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 400Mi
